### ISSUE TITLE
Vue 3 Error

### ISSUE THREAD

**Issue by dpVCent** [ckpack/vue-color#15]
Error when i tried the example provided in the readme.

color.js:34 Uncaught TypeError: Cannot read properties of undefined (reading 'h')
    at _colorChange (color.js:34:26)
    at Proxy.data (color.js:72:12)
    at applyOptions (runtime-core.esm-bundler.js:2791:34)
    at finishComponentSetup (runtime-core.esm-bundler.js:7170:9)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7082:9)
    at setupComponent (runtime-core.esm-bundler.js:7012:11)
    at mountComponent (runtime-core.esm-bundler.js:4922:13)
    at processComponent (runtime-core.esm-bundler.js:4897:17)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at mountChildren (runtime-core.esm-bundler.js:4685:13

**Comment by ckvv** [comment]
@dpVCent 
can you provide an example？

**Comment by dpVCent** [comment]
<script setup>
import HelloWorld from './components/HelloWorld.vue'
import TheWelcome from './components/TheWelcome.vue'
</script>

<template>
  <header>
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />

    <div class="wrapper">
      <HelloWorld msg="You did it!" />
        <Sketch :value="colors"/>
    </div>
  </header>

  <main>
    <TheWelcome />
  </main>
</template>

<script>
import { Sketch } from '@ckpack/vue-color';
export default {
  components: [
    Sketch,
  ],
  setup() {
    return {
      colors: '#194D33A8' // etc: { h: 150, s: 0.66, v: 0.30 }, { r: 255, g: 0, b: 0 }, '#194d33'
    }
  },
}
</script>

**Comment by ckvv** [comment]
you need change `:value` to `: modelValue ` or `v-model`

**Comment by dpVCent** [comment]
@ckvv I left it there by mistake, the same with v-model
![ex](https://user-images.githubusercontent.com/103255828/163319571-e41f89cb-0ff1-4f3d-9181-37c11bb5b5dc.png)

**Comment by ckvv** [comment]
@dpVCent 
What I tested is ok, you need to provide specific code to reproduce the problem

https://codesandbox.io/embed/happy-noyce-9xdh1o?fontsize=14&hidenavigation=1&theme=dark

**Comment by dpVCent** [comment]
@ckvv 
It works with the sandbox code, i removed the script setup in my code and it works
