### ISSUE TITLE
It crushes，when I import it on demand.

### ISSUE THREAD

**Issue by HHN0609** [ckpack/vue-color#18]
My code looks like below：
~~~vue
<Sketch color="#FFFFFF"></Sketch>
~~~
~~~js
import { Sketch } from '@ckpack/vue-color';
~~~

**Comment by ckvv** [comment]
You need to use `modelValue` or `v-model`

```vue
    <Sketch v-model="color"/>
    <Sketch modelValue="#FFFFFF"/>
```

**Comment by HHN0609** [comment]
Thanks!

**Comment by HHN0609** [comment]
> You need to use `modelValue` or `v-model`
> 
> ```
>     <Sketch v-model="color"/>
>     <Sketch modelValue="#FFFFFF"/>
> ```

Thanks! I think it will be better if  this component can combine with `<input/>` tag.
