### ISSUE TITLE
引用报错

### ISSUE THREAD

**Issue by dongshihao666** [ckpack/vue-color#2]
![image](https://user-images.githubusercontent.com/29971202/127450936-2cb4c828-cd32-452e-accf-1794070c9fe3.png)
![image](https://user-images.githubusercontent.com/29971202/127450986-5be9d037-930e-423a-b0e0-383e922eac83.png)

辛苦帮忙看看什么问题

**Comment by dongpeng520** [comment]
改成 v-model

**Comment by chenkai0520** [comment]
改成` v-model`或者`modelValue`
