### ISSUE TITLE
Is there no callback function

### ISSUE THREAD

**Issue by lixiaosaKk** [ckpack/vue-color#21]
I noticed that in vue color of vue2 version, there is @ input callback function

 Is there no callback function in ckpack/vue color
look forward to your reply

**Comment by lixiaosaKk** [comment]
I've tried @input and @inputChange, but unfortunately, they don't work

**Comment by lixiaosaKk** [comment]
Thank you for your answer

**Comment by lixiaosaKk** [comment]
I noticed that @ update: modelValue will trigger this method continuously during the color selection process, but I need to trigger it only at the last time. My solution is to use anti shake. Do you have a better solution

**Comment by lixiaosaKk** [comment]
Yes, thank you for your answer

**Comment by lixiaosaKk** [comment]
Yes, thank you for your answer

**Comment by ZedCoding** [comment]
> Yes, the event `@update:modelValue` fires immediately when the color changes, you need to add your own throttle function

![image](https://github.com/ckpack/vue-color/assets/24578758/749365fd-e8b5-4074-8f34-659ffe2d7f5f)
<Sketch v-model="color" @update:modelValue="onColorChange" />  throttle  not work?
