### ISSUE TITLE
render error

### ISSUE THREAD

**Issue by StarHosea** [ckpack/vue-color#3]
![image](https://user-images.githubusercontent.com/5615409/132598854-00d6bc10-d3af-465f-b7de-5137da20196e.png)

Problem:
[Vue warn]: Component is missing template or render function. 
  at <EditableInput label="a" value=1 arrow-offset=0.01  ... > 
  at <Sketch modelValue="" onUpdate:modelValue=fn > 

Enviroment:
Vue: 3.2.7.

**Comment by chenkai0520** [comment]
@StarHosea 
I tested it  is ok， this is the [demo](https://codesandbox.io/s/little-surf-h3m6w?file=/src/App.vue), 
can you give a recurring example？

**Comment by admins123C** [comment]
确实 我也出现了这个问题 联系我请加微信c1316497521

**Comment by admins123C** [comment]
![1632723125(1)](https://user-images.githubusercontent.com/85154838/134853787-fdcd240d-acc7-48cd-a1e1-72bf98297951.png)
![1632723197(1)](https://user-images.githubusercontent.com/85154838/134853880-3966e6e8-c1f7-4df8-981b-f59af2f2ee13.png)
![1632723190(1)](https://user-images.githubusercontent.com/85154838/134853907-f1153fa4-a764-4f2d-82b8-31f650b042d3.png)
![1632723180(1)](https://user-images.githubusercontent.com/85154838/134853917-6182876b-ab17-4d28-9c87-2d2567561bb5.png)
![1632723267(1)](https://user-images.githubusercontent.com/85154838/134853987-77be3b44-4d04-49f5-97bc-680d185bb781.png)
就是这种情况！！！！！！请尽快回复

**Comment by chenkai0520** [comment]
@admins123C 
<img width="949" alt="截屏2021-09-27 下午2 46 19" src="https://user-images.githubusercontent.com/30174970/134857825-59800fd0-e7ee-4e62-9cfc-f4e529477f48.png">

这个例子<https://codesandbox.io/s/little-surf-h3m6w?file=/src/App.vue>是没问题，我希望你可以提供一个可以重现问题的链接
