### ISSUE TITLE
In the [1.0.0- 1.1.3] version, some components do not take effect in the production environment.

### ISSUE THREAD

**Issue by zhongyingmin** [ckpack/vue-color#5]
![image](https://user-images.githubusercontent.com/49851699/138032159-75721604-5664-438e-9bcd-b208066cdfe9.png)

**Comment by ckvv** [comment]
@zhongyingmin 你能提供一个复现问题的git仓库吗？有人遇到过这个问题，但是我测试的是没问题的<https://codesandbox.io/s/little-surf-h3m6w?file=/src/App.vue>

**Comment by 4spen** [comment]
Hello, I have same issue with chrome picker

![image](https://user-images.githubusercontent.com/17015682/138076169-81906752-d722-492c-85c2-397ad9ec246d.png)
![image](https://user-images.githubusercontent.com/17015682/138076219-8c9cddde-b247-4174-b212-d4e64eb6d361.png)
