### ISSUE TITLE
console 输出一下警告，这个怎么需要怎么解决？

### ISSUE THREAD

**Issue by Beipy** [ckpack/vue-color#6]
![](https://ftp.bmp.ovh/imgs/2021/12/118dc8c831e3eb26.png)

**Comment by ckvv** [comment]
@Beipy 可以使用这个<https://www.npmjs.com/package/default-passive-events>消除警告

**Comment by Beipy** [comment]
怎样去做？是这样？

使用npm管理器下载default-passive-events依赖包

`npm i default-passive-events -S`

入口文件main.js引入

`import 'default-passive-events'`

**Comment by ckvv** [comment]
@Beipy 只能全局引入`default-passive-events`就可以，重写了全局方法，
