### ISSUE TITLE
ES Module support

### ISSUE THREAD

**Issue by motla** [ckpack/vue-color#9]
Hi,

I use your package as a dependency to my [vue-file-toolbar-menu](https://github.com/motla/vue-file-toolbar-menu) package, and it has been reported if fails to run under Vite.js `dev` server, because the tinycolor2 dependency you are using is not in ESM format, and Vite.js dev server does not support CommonJS modules.

Luckily, there is a fork of tinycolor2 rewritten in ESM : https://github.com/scttcper/tinycolor
With a little bit of modification, you could move to this fork.

Is it gonna happen? 🙂 

_Originally posted by @alex-maereanu in https://github.com/motla/vue-file-toolbar-menu/issues/16#issuecomment-1031599507_

Thank you

**Comment by ckvv** [comment]
@motla 

In version v1.1.6 I replace tinycolor2 with @ctrl/tinycolor，
As another workaround,  You also can Use `optimizeDeps.include` to force a linked package to be pre-bundled.

```js
export default defineConfig({
  plugins: [vue()],
  optimizeDeps: {
    include: ['@ckpack/vue-color'],
  }
});
```

**Comment by motla** [comment]
Thanks a lot!!

**Comment by ckvv** [comment]
@motla  Dependencies have been updated

**Comment by motla** [comment]
Great, this time it works. Thank you!

**Comment by ckvv** [comment]
@flapili 
Can you provide an example? @ckpack/vite can be used in vite.

**Comment by flapili** [comment]
@ckvv 
```vue
<script setup>
import { Slider, Twitter } from '@ckpack/vue-color'
</script>

<template>
  <div />
</template>
```

it work as excepted with vite but not with vite-ssg :/
is `@ckpack/vue-color` ssr friendly ?

**Comment by ckvv** [comment]
@flapili 
According to the log, it seems that vite-ssg has installed `@ckpack/vue-color` to CommonJS module,. I will update it later to clarify the export type

**Comment by flapili** [comment]
> @flapili According to the log, it seems that vite-ssg has installed `@ckpack/vue-color` to CommonJS module,. I will update it later to clarify the export type

monkeypatching in package.json of the package `  "type": "module",` did the trick , is it the right solution ?

**Comment by ckvv** [comment]
@flapili 
Yes, I added it in `"@ckpack/vue-color": "^1.2.0"`
